# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DAX": "00_core.ipynb",
         "STOXX": "00_core.ipynb",
         "VSTOXX": "00_core.ipynb",
         "SetupLogger": "00_core.ipynb",
         "printWhenExecuting": "00_core.ipynb",
         "printinstance": "00_core.ipynb",
         "Activity": "00_core.ipynb",
         "RequestMgr": "00_core.ipynb",
         "Client": "00_core.ipynb",
         "Wrapper": "00_core.ipynb",
         "write_contract_to_mongo": "00_core.ipynb",
         "App": "00_core.ipynb",
         "start_stream": "00_core.ipynb"}

modules = ["tws_data.py"]

doc_url = "https://Wilhelm Fritsche.github.io/tws_data/"

git_url = "https://github.com/Wilhelm Fritsche/tws_data/tree/master/"

def custom_doc_links(name): return None
